### PR TITLE
Support Ruby 3.0

### PR DESCRIPTION
**Pull request by orien**
Running `sparkle_formation` on Ruby 3.0 results in the following runtime error.

```
RuntimeError: The `SortedSet` class has been extracted from the `set` library.You must use the `sorted_set` gem or other alternatives.
(eval):107:in `require'
(eval):107:in `const_get'
(eval):107:in `block (2 levels) in eval_wrapper'
(eval):104:in `each'
(eval):104:in `block in eval_wrapper'
./lib/sparkle_formation/sparkle.rb:68:in `class_eval'
./lib/sparkle_formation/sparkle.rb:68:in `block in eval_wrapper'
./lib/sparkle_formation/sparkle.rb:66:in `instance_exec'
./lib/sparkle_formation/sparkle.rb:66:in `eval_wrapper'
./lib/sparkle_formation/sparkle.rb:251:in `initialize'
------------------
--- Caused by: ---
LoadError: cannot load such file -- sorted_set
(eval):107:in `require'
```

Avoid this problem by not copying across the `SortedSet` constant in the eval wrapper.

### CODE REVIEW

**Comment by orien** [comment]
@chrisroberts Could I please get your opinion on this?

It would be great to get this project working on Ruby 3.

**Review by stevehodgkiss — APPROVED** [review]

**Comment by slyness** [comment]
It would indeed be great to get updated with support for a more recent ruby. I am going to review and try and get it updated soon.

**Comment by slyness** [comment]
@chrisroberts will there be any more releases? Or discuss a way to support more release maintainers?

**Comment by chrisroberts** [comment]
This is currently fixed on main. I've been working through all the supporting libs to get them compatible with ruby 3. I'm wrapping up with sparkle_formation and sfn now so a new release addressing ruby 3 issues will be coming shortly.

Cheers!

**Comment by petervandoros** [comment]
@chrisroberts I see that this issue was resolved, along with others, in November last year. Is it possible to release an updated version of the gem?

**Pull request closed without merging**
