### PR TITLE
Fix the case where sub! is invoked without a variables hash

### LINKED ISSUE #222: AWS sub! should allow single argument
It looks like the AWS `sub!` helper should support being called with just a single parameter (no map) when substituting just template parameters as the real `!Sub` function supports this.

```ruby
sub!("region is ${AWS::Region}")        # errors due to 2 args required
# => !Sub "region is ${AWS::Region}"    # intended working output
```

From [!Sub documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html)
> If you're substituting only template parameters, resource logical IDs, or resource attributes in the String parameter, don't specify a variable map.

I'm using a simple work-around for the moment:
```ruby
sub!("region is ${AWS::Region}", not: "used")
# => !Sub ["region is ${AWS::Region}", {"Not": "used"}]
```

### PR DESCRIPTION
**Pull request by devkid**
This should fix #222.

### CODE REVIEW

**Comment by devkid** [comment]
@chrisroberts Any thoughts?

**Comment by devkid** [comment]
Is it possible to get a bugfix release for that? :slightly_smiling_face:

**Comment by manikantakrishna** [comment]
I'm not able to pass the string without the variable hash.
which version issue was fixed?

**Comment by devkid** [comment]
3.0.28, see changelog.

**Pull request merged**
