### PR TITLE
a typo often ends up creating structs that then make other names brea…

### PR DESCRIPTION
**Pull request by grosser**
…k ... adding a sanity check to make these errors easier to spot

@chrisroberts

### CODE REVIEW

**Comment by chrisroberts** [comment]
The idea is sound but the implementation would break expected functionality as no struct values would be allowed to be passed within the configuration hash. Would be better to type check on the specific items that are cared about, using the expected types. Raising a type error would be a better fit as well. Will use this as a starting point and make adjustments. Thanks!

**Comment by grosser** [comment]
I don't expect any meaningful / good solution to be 100% compatible ... we are using this now, which works pretty well ... does not allow chaining like `foo.bar.baz` (can be rewritten as nesting) but blocks all kinds of method missing calls since they usually look like:

```
foobar insert_typo_here
```

```Ruby
# calling methods without arguments or blocks smells like a method missing
::SparkleFormation::SparkleStruct.prepend(Module.new do
  def method_missing(name, *args, &block)
    caller = ::Kernel.caller.first

    called_without_args = (
      args.empty? &&
      !block &&
      caller.start_with?(File.dirname(File.dirname(__FILE__))) &&
      !caller.include?("vendor/bundle")
    )
    internal_method = (name =~ /^_|\!$/)

    if called_without_args || internal_method
      message = "undefined local variable or method `#{name}` (use block helpers if this was not a typo)"
      ::Kernel.raise NameError, message
    end
    super
  end
end)
```

**Comment by grosser** [comment]
FYI switched to allowing only uppercase methods 
 - easy to see what is a method and what is an attribute
 - closer to original cloudformation / easier to paste
 - no camel-case bugs

```Ruby
# make our templates only support know keys
::SparkleFormation::SparkleStruct.prepend(Module.new do
  def method_missing(name, *args, &block)
    # using upcase attribute names is fine / cannot be confused with method calls
    return super if name =~ /^[A-Z]/

    # ok for sfn itself / any other gem
    return super if ::Kernel.caller.first.include?('/gems/')

    # not ok for us to use bad names
    ::Kernel.raise NameError, "undefined local variable or method `#{name}`"
  end
end)
```

**Comment by chrisroberts** [comment]
If this works for your specific use case then that's great. For the library at large this introduces multiple breaking changes as well as reduces the functionality of the DSL itself:

* Project specific naming conventions _can_ aid in easy identification of "attributes"
* CloudFormation is not the only supported template format
* SparkleFormation itself is aimed at reducing copy/paste not enabling it
* Explicit sets work fine for handling non-conventional casing styles 
* Restricting to only capitalized methods breaks method chaining

Cheers!

**Pull request closed without merging**
