### PR TITLE
make debugging easy

### PR DESCRIPTION
**Pull request by grosser**
atm calling puts / raise creates and attribute ... so there is no easy way to debug things, especially not for people that are new to ruby ... so make it easy / straight forward by defining at least puts and raise

@chrisroberts

... ideally get rid of this whole method missing foobar and only allow predefined methods + attribute :xyz, 123 for one-offs as sinatra / capistrano etc frameworks do ... overriding everything looks nice but is super hard to debug once something goes wrong ...

(reopened #106 against develop)

### CODE REVIEW

**Comment by chrisroberts** [comment]
Hi! Thanks for this PR but this is not something that can be merged as it would introduce a breaking change as well as remove expected functionality from within the DSL context. I would be open to providing `puts!` and `raise!` helper methods in place of these. I'll also add a documentation page with "debugging tips" to provide some easily accessible information around generating stdout output from within the DSL and accessing constants, etc.

From the side discussion in #106, the usage of `#method_missing` within this library is fundamental to its functionality. Removing this in favor of pre-defined methods + the introduction of an `attribute` method for everything else would break all existing usages of this library, and heavily reduce the readability and usability of the DSL (the majority of the file would consist of `attribute` calls). 

Cheers!

**Comment by grosser** [comment]
Do you think anyone uses puts and raise as attributes ?

**Comment by grosser** [comment]
Updated to use puts! and raise! ... can you reopen and merge ?

**Comment by grosser** [comment]
instead of method missing it could also hashes like

```
foobar(
  bar: 1
  foo: 2
)
```

would also make drying up things easier ... of course this would have to be  new version or opt-in feature ... but yeah ... not an easy change to make ...

**Comment by grosser** [comment]
I think the changes I pushed don't show because it's closed ... hopefully they show once it's reopened ...

**Comment by grosser** [comment]
@chrisroberts can you reopen and merge ?

**Comment by chrisroberts** [comment]
Removing the `method_missing` functionality is a non-starter as it would not only break any existing usages of the library, but it would also remove the fundamental functionality that the library provides. If using Hash values to generate the template is preferred, the DSL does not restrict that sort of implementation. However, I would argue at that point there would be little gain over just writing it directly in JSON. 

I cannot re-open this PR. It looks like GH won't allow re-opening a PR if the requester branch has been force pushed (didn't know GH had this behavior) so if you create a new PR I can merge that. Thanks!

**Comment by grosser** [comment]
reopened https://github.com/sparkleformation/sparkle_formation/pull/111

**Pull request closed without merging**
