### PR TITLE
Add support for amazon activemq service

### PR DESCRIPTION
**Pull request by tsunam2**

### CODE REVIEW

**Comment by tsunam** [comment]
Just checking in on this as there hasn't been much of anything on this and sure there are multiple folks who'd like to have this support added in.

**Comment by tsunam2** [comment]
Just checking in on this as there hasn't been much of anything on this and sure there are multiple folks who'd like to have this support added in.

**Comment by tsunam2** [comment]
Appears you did this via https://github.com/sparkleformation/sparkle_formation/commit/30ace08169ec46d88267abddaf526645e5a552fe instead of using this pull request.

Just curious if there was anything that could have caused you to not pull this pr in at the time?

**Comment by chrisroberts** [comment]
@tsunam2 Hi! Thanks for the PR, and sorry it took me so long to get this updated. The resource files are not manually updated, rather they get auto generated using the helper scripts in the `./bin` directory of this repository. Nothing wrong at all with the PR, it's just the process used to update the files. Thanks again!

Cheers!

**Pull request closed without merging**
