### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by grosser**
@chrisroberts 

this will build each PR and let you know if the tests pass on major versions of ruby

also helps contributors instantly see if what they added breaks anything

only thing you need to do is activate it on https://travis-ci.org/profile

### CODE REVIEW

**Comment by grosser** [comment]
@chrisroberts can you add travis ?

**Comment by grosser** [comment]
@chrisroberts is this looking good ?

**Comment by grosser** [comment]
@chrisroberts any love for CI ?

**Comment by bhouse** [comment]
:+1:

**Comment by grosser** [comment]
@chrisroberts a :+1: / :-1: would be great!

**Comment by luckymike** [comment]
@grosser @bhouse Thanks for the PR.

We're ambivalent about this right now, which is why it's not gotten attention. In the future we'll probably revisit or address CI via another route, but at the moment our attention is elsewhere. 

Closing without prejudice to remove ambiguity about our current intentions. :)

**Pull request closed without merging**
